#!/bin/sh
### BEGIN INIT INFO
# Provides:          github-webhook
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: GitHub Webhook Listener
# Description:       Runs the Rust webhook listener for git events.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="GitHub Webhook Listener"
NAME="github-webhook"
DAEMON=/usr/local/bin/github-webhook-listener
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Read configuration from /etc/default/
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
    export WEBHOOK_SECRET=$WEBHOOK_SECRET
    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON \
        --background --make-pidfile --chuid $USER --oknodo
}

do_stop() {
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
    rm -f $PIDFILE
}

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    do_start
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    do_stop
    log_end_msg $?
    ;;
  restart|force-reload)
    do_stop
    sleep 1
    do_start
    ;;
  status)
    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|status}" >&2
    exit 3
    ;;
esac